### ISSUE TITLE
The .shortcut import problems

### ISSUE THREAD

**Issue by TheUnch0senOne** [gonzula/splash#22]
I have already seen 

> 2

of the issues in the Shortcut app, where it does not support importing shortcuts as files.

I **do not** actually have an idea on how to program it into the app, but _i have a possibly working and possible_ idea:

1. 

You can use shortcuts to get icloud links, so you can add a link to a shortcut that makes the iCloud link in the app/etc.

2.

And let the app compile the .splash file into .shortcuts.

3.

Then, simply let the user **download** the file.

I honestly do not know if this is possible is Xcode, I’m not really a programmer so, yeah try this idea if you want lol.

e

**Comment by pfgithub** [comment]
This can be done. ScPL uses a similar shortcut for importing from a QR code: https://www.icloud.com/shortcuts/eb304f320ee94bef9cba24d2201a91d7

**Comment by TheUnch0senOne** [comment]
@gonzula When are you going to fix this issue? It has been a whole MONTH now.

**Comment by flavioheleno** [comment]
Chill @TheUnch0senOne, dude has other stuff to do as well.

**Comment by TheUnch0senOne** [comment]
![IMG_0879](https://user-images.githubusercontent.com/63002752/82517056-d74b1d80-9b4e-11ea-8a5c-74d59260e992.jpeg)
Yea, I'll let the dude do his thing.
###### I'm gonna get hate now, huh. oki

**Comment by flavioheleno** [comment]
Hey @TheUnch0senOne, there's already a lot of hate out there brother, no need for more in here..just be cool :-D

Take care man, cheers!

**Comment by TheUnch0senOne** [comment]
I'm already used to hate, but thanks! @flavioheleno
