### ISSUE TITLE
A little typo, nothing to worry about.

### ISSUE THREAD

**Issue by TheUnch0senOne** [gonzula/splash#23]
[Photo of typo](https://i.imgur.com/crXDRuF)
Yes, it is a very small problem.
“Simple Programming _LAnguage_ for _SHortcuts_“
to
“Simple Programming _Language_ for _Shortcuts_”
in the iOS app’s help menu.

**Comment by ismailbgr** [comment]
If you take that uppercase letters and put side by side you'll realise it becomes

SPLASH

so this is intentional not a typo

**Comment by TheUnch0senOne** [comment]
Closed, due to the reason:
I was stupid.
