### ISSUE TITLE
All input files generate "syntax error"

### ISSUE THREAD

**Issue by milo526** [gonzula/splash#6]
All examples and the simplest of own creation for input files create a "syntax error" on compilation with the exception for an empty file.
However the shortcut builds as expected and works when airdropped to device.

System: macOS 0.14.4 beta
Version: v0.1.1

Steps to reproduce

Example` input.splash`:

```
a := AskNumber()

ShowResult(a)
```

1) Build or download binary
2) Run `./splash input.splash out`

Expected: No error
Actual result: "syntax error" and proper file creation

**Comment by gonzula** [comment]
Could you please paste a hexdump of your `input.splash` file?
The command `hexdump input.splash | pbcopy` will copy the dump to your pastboard and you can paste the output here.

The only way I managed to reproduce a "syntax error" with this input file was by using `CRLF (\r\n)` line endings, but they are not very common on macOS.

The compiler in fact doesn't recognise `\r` and I'm already fixing that, but that might not be the only issue.

**Comment by gonzula** [comment]
Actually I think the problem is that your file doesn't end with a `\n`. I'm working on that fix, but in the meanwhile you can add a line break at the end of your scripts and it should work.

**Comment by milo526** [comment]
Appending an extra newline indeed removed the syntax error

Hexdump without newline:
```
0000000 61 20 3a 3d 20 41 73 6b 4e 75 6d 62 65 72 28 29
0000010 0a 0a 53 68 6f 77 52 65 73 75 6c 74 28 61 29
000001f
```

The above mentioned merge request does indeed seem to fix the problem, the aforementioned file does not give a syntax error after making the new master branch.

Thanks for the fast fix.
